/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'TAKUMI' at '17/04/09 23:24' with Gradle 2.14.1
 *
 * @author TAKUMI, @date 17/04/09 23:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
